---
- name: Install EPEL release for nginx
  yum:
    name: epel-release
    state: present

- name: Install nginx web server
  yum:
    name: nginx
    state: latest

- name: start nginx
  service:
    name: nginx
    state: started